version: '3.3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=spotify_matcher"
    ports:
      - "5432:5432"