spring:
  jpa:
    properties:
      driver-class-name: org.postgresql.Driver
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        hbm2ddl:
          auto: create

  liquibase:
    enabled: false

client:
  id: itest
  secret: itest

rsa:
  private:
    key: itest
  public:
    key: itest

admin:
  password: yes